#!/usr/bin/env python3
from datetime import UTC, datetime
from pathlib import Path


SITES = [
    ("carta-astral", "carta-astral-gratis.es"),
    ("compatibilidad-signos", "compatibilidad-signos.es"),
    ("tarot-del-dia", "tarot-del-dia.es"),
    ("calcular-numerologia", "calcular-numerologia.es"),
    ("horoscopo-de-hoy", "horoscopo-de-hoy.es"),
]


def main():
    updated = datetime.now(UTC).strftime("%Y-%m-%dT%H:%MZ")
    rows = "\n".join(
        f"| `{site}` | `https://{domain}/` | `https://{domain}/sitemap.xml` |"
        for site, domain in SITES
    )
    content = f"""# Astro Cluster Ops Status

Generated by `.github/scripts/update_ops_status.py`.

Last update: `{updated}`

## Production Sites

| Site | Primary URL | Sitemap |
| --- | --- | --- |
{rows}

## Free-Tier Friendly Defaults

- Deploys run only for changed sites or manual target selection.
- Lighthouse is manual opt-in with `run_lighthouse=true`.
- SEO smoke runs on weekdays and opens/updates issues instead of failing silently.
- GSC sitemap submission is non-blocking after deploy.
- AdSense auto ads stay disabled unless `ADSENSE_AUTO_ADS_ENABLED` is explicitly enabled.

## Operational Sources

- Growth snapshot: `docs/GROWTH_MILESTONES.json`
- Public stats: `sites/carta-astral/public/stats.json`
- DNS notes: `docs/DNS.md`
- Workflows: `.github/workflows/`
"""
    Path("docs/OPS_STATUS.md").write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
